name: Build FreeBsd Release

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build FreeBsd
    steps:
    - uses: actions/checkout@v4
    - name: Build Release
      uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        release: 13.2
        prepare: |
          pkg install -y node wget curl git bash gawk gsed zip www/npm
        run: |
          git clone https://github.com/louislam/uptime-kuma.git 
          cd uptime-kuma
          git checkout 1.23.13 && npm ci --production && npm run download-dist
          zip -r uptime-kuma.zip .

          
    - name: Upload artifact
      uses: actions/upload-artifact@main
      with:
        name: uptime-kuma-freebsd
        path: |
            uptime-kuma/uptime-kuma.zip

    - name: Generate release tag
      id: tag
      run: echo "release_tag=v0.0.5" >> $GITHUB_OUTPUT

    - name: Create release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.ANY_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        files: |
              uptime-kuma/uptime-kuma.zip
              

