name: Run Sync

on:
  schedule:
    - cron: '0 16 */1 * *'
  workflow_dispatch:

jobs:
  Sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: compare versions
        run: |
          export REMOTEVERSION=$(wget -qO- https://github.com/louislam/uptime-kuma/tags | gawk -F '["v]' '/name/{print "v"$5;exit}')
          export LOCALVERSION=$(curl --location --silent --fail --show-error "https://api.github.com/repos/gordonchanfz/uptime-kuma/releases/latest" | grep -oP '"tag_name":\s*"\K[^"]+')
          bash checkversion.sh
          
      - name: Trigger release
        if: ${{ env.SYNCED == 0 }}
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.ANY_TOKEN }}
          script: |
              await github.rest.actions.createWorkflowDispatch({
              owner: 'gordonchan',
              repo: 'uptime-kuma',
              workflow_id: 'freebsd-release.yml',
              ref: 'main'
              })
              
      - name: Delete workflow runs
        if: ${{ env.SYNCED == 1 }}
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.ANY_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 8
